### ISSUE TITLE
Description of USB_ReadPMA is incorrect (copy/past error from USB_WritePMA)

### ISSUE THREAD

**Issue by kasjer** [STMicroelectronics/STM32CubeF1#13]
Description of function is incorrect it should be copy **from** PMA not user buffer
https://github.com/STMicroelectronics/STM32CubeF1/blob/5ddefcd6a64e793087436cc4ed42abd1886952c1/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_ll_usb.c#L2538

**Comment by ALABSTM** [comment]
Hi @kasjer,

Thank you for having reported this point. You are right. It seems to be a "copy-paste" error. Your remark will be transmitted to our development teams to have this comment updated.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 87005
