### ISSUE TITLE
gcc Startup files don't initialize stack pointer

### ISSUE THREAD

**Issue by ftapajos** [STMicroelectronics/STM32CubeF1#17]
I'm not sure if that is an issue, because it seems too critical to be in the code for that long, but the stackpointer is not being set anywhere in the reset_Handler subrountine for any of the startup_stm32f1xxxx.s files in the gcc folder

**Comment by ALABSTM** [comment]
Hi @ftapajos,

Thank you for your question. It seems you will find your answer here (#5). Do not hesitate in case you still face an issue.

With regards,

**Comment by ALABSTM** [comment]
Hi @ftapajos,

Did you find the answer you are looking for here (#5)?

With regards,

**Comment by ALABSTM** [comment]
Hi @ftapajos,

Please allow me to close this issue. You can reopen it or open a new one in case you face any problem related to this subject.

With regards,
