### ISSUE TITLE
STM3210C_EVAL: LCD module image corruption with BSP Example 

### ISSUE THREAD

**Issue by Patel-Arpan** [STMicroelectronics/STM32CubeF1#20]
**Setup**
 * STM3210C_EVAL (Checked on 3 different boards)
 * STM32CubeIDE 1.3
 * Project: STM32CubeF1\Projects\STM3210C_EVAL\Examples\BSP

**Description of the bug**
The BSP Example initializes and setups the LCD module but the image is corrupted in the bottom section of the display. I have verified on 3 boards, no changes in the source code. Please see the attached image-1.
I have verified the LCD module is working fine with [the demonstration firmware](https://www.st.com/content/st_com/en/products/embedded-software/mcu-mpu-embedded-software/stm32-embedded-software/stm32-standard-peripheral-library-expansion/stsw-stm32042.html) of STM3210C_EVAL board. Please see the attached image-2.

**How To Reproduce**
1. Import the project in STM32CubeIDE from location STM32CubeF1\Projects\STM3210C_EVAL\Examples\BSP.
2. Build and Flash the Project. You should see image corruption on the LCD module.
2. BSP and LCD modules - are cause for the issue.

**Additional context**
I am new to STM32 platform, won't be able to solve it at present but I can test the solution for you on my boards.

**Screenshots**
![Image-1 Corruption](https://user-images.githubusercontent.com/64938527/88000539-7ecad900-cb1b-11ea-8eb4-9c9cc6b87f42.jpeg)
![Image-2 Demo Fw](https://user-images.githubusercontent.com/64938527/88000550-85f1e700-cb1b-11ea-94cd-93c76f5a9830.jpeg)

**Comment by RKOUSTM** [comment]
Hi @Patel-Arpan,

We are very pleased with the interest you show to our products. However, this public organization on GitHub is intended to promote co-development and issues posted here shall exclusively be related to the software published within the different repositories.
For any other issue (e.g. related to documentation, to hardware, to ecosystem, to user application, etc.), you shall address your questions to the [ST Community](https://community.st.com/s/topiccatalog). There you shall look for the adequate topic and submit your question or remark. 

With regards,
