### ISSUE TITLE
error: expected expression __HAL_TIM_SET_CAPTUREPOLARITY(__HANDLE__, __CHANNEL__, __POLARITY__)  

### ISSUE THREAD

**Issue by ZhaoYandong00** [STMicroelectronics/STM32CubeF1#21]
When I use the function, I find MDK_ARM reports an error(error: expected expression ).Review the function,I find that  this function( TIM_RESET_CAPTUREPOLARITY ) uses  an extra ')`.

**Comment by ASELSTM** [comment]
Hi @ZhaoYandong00, 

Thank you for your contribution.

Actually, the point you raised is already known. It has been internally fixed. The fix will be published in the frame of a future publication.

With regards,

**Comment by ALABSTM** [comment]
ST Internal Reference: 80370

**Comment by ALABSTM** [comment]
Duplicate of #18.
