### ISSUE TITLE
Error template with FatFs syscall.c

### ISSUE THREAD

**Issue by Coloryr** [STMicroelectronics/STM32CubeF1#50]
Pack Version: 1.8.4

The generated template file cannot be used with FreeRTOS.
This problem occurs in the F1 chip. The H7 chip is normal.
F1:
![_~8MGSB{)7VLOVH4C773DNR](https://user-images.githubusercontent.com/26276037/173472620-f8cdcde5-118c-4217-8fe5-44ebc16036d0.png)

H7:
![EHSR C7R{`J(81IK2YSP{FD](https://user-images.githubusercontent.com/26276037/173472527-3802e380-fcb0-401d-a097-4c7f9b18ef2b.png)

**Comment by HBOSTM** [comment]
Hello @Coloryr ,

This point has been reported to our development teams for deeper analysis. We will get back to you as soon as we have updates.

With Regards,

**Comment by HBOSTM** [comment]
ST Internal Reference: 145227

**Comment by RJMSTM** [comment]
Hello @Coloryr 

There is no plan to upgrade MW for legacy STM32 series.

With Regards,
Rania
