### ISSUE TITLE
Refactor CMSIS includes

### ISSUE THREAD

**Issue by Devilbinder** [STMicroelectronics/STM32CubeF1#51]
I came across redundant `else` statements and some `if` statements that can be reworked by flapping them, in the CMSIS include folder. I believe this will increase the readability and reduce the overall footprint of the code with regards to the amount of lines.   

Here is a examples one of the many functions that do this.

https://github.com/STMicroelectronics/STM32CubeF1/blob/218b5100dd9e4b9bb3b0aa7fc77467373e932025/Drivers/CMSIS/Include/core_cm1.h#L667

This can be refactored too:

```c
__STATIC_INLINE uint32_t __NVIC_GetEnableIRQ(IRQn_Type IRQn)
{
  if ((int32_t)(IRQn) >= 0)
  {
    return ((uint32_t)(((NVIC->ISER[0U] & (1UL << (((uint32_t)IRQn) & 0x1FUL))) != 0UL) ? 1UL : 0UL));
  }
    return (0U);
}
```
If this is of interest. I have a branch the can be summited as a PR https://github.com/Devilbinder/STM32CubeF1/tree/refactor.

**Comment by ASELSTM** [comment]
Hi @Devilbinder,

The files within CMSIS include folder are out of scope of STMicroelectronics as they are provided by ARM. All changes and updates to these files are not managed by our technical team but rather by ARM's team. Therefore, you may report this issue on [ARM](https://github.com/ARM-software) GitHub.

Please allow me then to close this issue and hank you for your contribution.

With regards,
