### ISSUE TITLE
Update STM license to SLA0048?

### ISSUE THREAD

**Issue by stephenkilbaneadi** [STMicroelectronics/STM32CubeF1#56]
LICENSE.md describes some of the files as being licensed under SLA0044. If the same package is retrieved from st.com, the license presented is SLA0048. Should SLA0044 be updated to SLA0048, in this repo?

**Comment by ALABSTM** [comment]
Hi @stephenkilbaneadi,

Thank you for this question. Actually, the **SLA0048** is the license applicable to the overall firmware, while the **SLA0044** is specific to some components, as you pointed out. Hence, there is no typo and no need to change SLA0044 into SLA0048.

The **SLA0048** is particularly used when users download the firmware from www.st.com, as there is no possibility for them to browse the firmware content and check each component's individual license before downloading it in this case.

On the other hand, as browsing before downloading is possible on www.github.com, there is no need to display this "global" license. Users can directly check each component's license individually. The LICENSE.md file at the root of this repo simply makes it easier to have an overview at a glance.

I hope this answers your question.

With regards,
