### ISSUE TITLE
Compiler warning for unused parameters in stm32f1xx_ll_adc.h

### ISSUE THREAD

**Issue by IvanSojic** [STMicroelectronics/STM32CubeF1#64]
Prevent unused argument compilation warnings (with some compilers) when using stm32f1xx_ll_adc.h

**Potential solution**
* A solution would be to use UNUSED macro
![image](https://github.com/STMicroelectronics/STM32CubeF1/assets/103666553/a4a232a9-f08d-4464-a449-5897216e59f5)

**Open topic**
Where would be a good place to redefine UNUSED macro?
For HAL it is done inside stm32f1xx_hal_def.h

#if !defined(UNUSED)
#define UNUSED(X) (void)X      /* To avoid gcc/g++ warnings */
#endif /* UNUSED */

**Comment by RJMSTM** [comment]
Hello @IvanSojic,

Thank you for this report. We will get back to you as soon as we analyze it further. This may take some time. Thank you for your comprehension.

With Regards,

**Comment by RJMSTM** [comment]
Hello @Ivan,

Please can you precise the flags used in your example for better analysis? 

Thanks,
Rania

**Comment by IvanSojic** [comment]
Hi @RJMSTM 
Currently we have enabled "-Wall -Wextra" for gcc compiler.
Best regards, Ivan

**Comment by RJMSTM** [comment]
Hello,
for LL drivers you can use in stm32f1xx_ll_adc.h 
 
` (void)(ADCxy_COMMON);`

Regards,
Rania

**Comment by RJMSTM** [comment]
ST Internal Reference: 184950

**Comment by TOUNSTM** [comment]
Fixed in 42472d601caa457b02d849c7de5f9792629ee324
