### ISSUE TITLE
SET_BIT, CLEAR_BIT and MODIFY_REG are not atomic

### ISSUE THREAD

**Issue by IvanSojic** [STMicroelectronics/STM32CubeF1#67]
In systems using RTOS, functions SET_BIT and CLEAR_BIT are not atomic.

Since many macros from LL and HAL level are using SET_BIT and CLEAR_BIT functions, What is general recommendation in systems with RTOS?
We have also noticed implementation of ATOMIC_SET_BIT, ATOMIC_CLEAR_BIT, etc.  What is their intention, since they are mostly used only for UART driver?

Best regards, 
Ivan Sojic

**Comment by TOUNSTM** [comment]
Hello @IvanSojic,

First of all, please excuse this late reply.

1. SET_BIT and CLEAR_BIT macros are indeed not atomic
2. In case of RTOS usage, it is customer application responsibility to manage the protection of shared resources by the different threads (via mutex).
3. ATOMIC_SET_BIT and ATOMIC_CLEAR_BIT macros were introduced to handle the specific case where parallel processes in bare metal implementation may need to access the same register for interrupt control; this is the case of UART driver where you can run in parallel Rx & TX processes and all interrupts are being handle in CR1/CR3 registers causing side effects if accesses are not atomic.

I hope this answers your question. Please allow me to close this issue.

With regards,
