### ISSUE TITLE
F1 series chips lack freertos_mpool.h and freertos_os2.h files

### ISSUE THREAD

**Issue by keysking** [STMicroelectronics/STM32CubeF1#68]
After upgrading the F1 series package of STM32CubeIDE to version 1.8.6, I noticed that in newly created projects, the cmsis_os2.c file now includes references to freertos_mpool.h and freertos_os2.h. However, these two files are missing from the project.
![image](https://github.com/user-attachments/assets/77a96e23-0a4b-4a0f-bf24-36a1565c4179)

I managed to locate these files in the 1.8.6 package, but even after placing them in the project's CMSIS_RTOS_V2 directory, I encountered more errors.
![image](https://github.com/user-attachments/assets/56597cce-6dc6-429f-b10f-3b769fc0cd4e)

**Comment by TOUNSTM** [comment]
ST Internal Reference: 188615

**Comment by TOUNSTM** [comment]
Hello @keysking,

We confirm the abnormal behavior you reported. It has been reported to our development teams. A fix will be available in the frame of STM32CubeMX release 6.13.0. As there is no impact on the software provided within this repository, please allow me to close this issue.

Thank you for your comprehension.
With regards,
