### ISSUE TITLE
1.8.6 has a bug

### ISSUE THREAD

**Issue by 18268159377** [STMicroelectronics/STM32CubeF1#69]
FreeRTOS\Source\CMSIS_RTOS_V2\cmsis_os2.c:33:10: fatal error: freertos_mpool.h: No such file or directory

**Comment by TOUNSTM** [comment]
See Also https://github.com/STMicroelectronics/STM32CubeF1/issues/68

**Comment by TOUNSTM** [comment]
See Also https://github.com/STMicroelectronics/stm32_mw_freertos/issues/5

**Comment by TOUNSTM** [comment]
Hello @18268159377,

Thank you for your report. This point is related to the CubeMX generation problem and not directly related to the firmware published in this repository. A fix will be available in the frame of STM32CubeMX release 6.13.0. As there is no impact on the software provided within this repository, please allow me to close this issue.

Thank you for your comprehension.
With regards,

**Comment by Coloryr** [comment]
How to get the `STM32CubeMX release 6.13.0`?

**Comment by konrin** [comment]
@TOUNSTM Hi! How to get around this problem without waiting for the IDE release? I already need to work with cmsis v2.
Could you please provide steps to solve this problem?
